sudo: required

language: csharp
mono: none
dist: xenial
dotnet: 3.1

script:
  - dotnet restore
  - dotnet build
  - dotnet test --logger:"console;verbosity=detailed" --filter TestCategory=smoke

before_install:
  - openssl aes-256-cbc -K $encrypted_f40cd3181a7a_key -iv $encrypted_f40cd3181a7a_iv
    -in APIAutomationCore/TestSettings.json.enc -out APIAutomationCore/TestSettings.json -d
